### ISSUE TITLE
Add average trait value model 

### ISSUE THREAD

**Issue by habacucfm** [kwythers/acme_dist#9]
That is add a model per site that runs using the mean trait value from the 100 trait values distribution

**Comment by mchen0312** [comment]
I've done calculating the mean change the script. I submitted them just as before but this time seems to me there is issue with MSI (no response and no error message either), I've send out email to check will keep you guys updated.

**Comment by mchen0312** [comment]
Hi folks,

The run with mean trait values are up running. We should have results later tonight. It will be saved in the ACME_trait_dist directory as trait 101.
